feat: add pages to vite plugin for builder
frappe/frappe-ui pull request #135
Opened 2024-03-23 14:24 UTC by blaggacao

- requires by https://github.com/frappe/builder/blob/95493c56ce9e98cadca45c226c3efb51e781c36e/frontend/vite.config.js#L34

2024-03-24 03:15 UTC, surajshetty3416 commented
@blaggacao Why is this required here 🤔

2024-03-24 06:11 UTC, blaggacao commented
Ah, you're right. That's a better idea! Will do, shortly.

2024-03-24 14:44 UTC, blaggacao commented
@surajshetty3416 Does this look better?

Btw, I don't know why not this diff, but I left it how it was

```diff
module.exports = function proxyOptions({
  port = 8080,
  regex = '^/(app|login|api|assets|files)',
- } = {}) {
+ }) {
```

2024-03-25 01:17 UTC, surajshetty3416 commented
> Btw, I don't know why not this diff, but I left it how it was

the `{}` in it is just a default value so that you can call `proxyOptions()` (without any parameter) and still be able to destructure the object with default values (eg. port and regex).

2024-03-25 01:47 UTC, surajshetty3416 requested changes

2024-03-25 01:47 UTC, surajshetty3416 commented on vite.js
> +  regex = '^/(app|login|api|assets|files)',
```suggestion
  source = '^/(app|login|api|assets|files)',
```
Variable name "source" sounds more apt? 
like "all these sources are redirected to a different target"

2024-03-25 01:47 UTC, surajshetty3416 commented on vite.js
> +  proxy[regex] = {
```suggestion
  proxy[source] = {
```

2024-03-25 01:53 UTC, surajshetty3416 approved these changes

2024-03-25 01:56 UTC, merged