feat: Tree Component
frappe/frappe-ui pull request #173
Opened 2024-08-16 13:20 UTC by GursheenK

#### Description
Added a Tree Component which takes an object containing nested data to be rendered as a tree. 

#### Props 
1. **node** - root node ie. complete tree data where each node consists of the label and and it's children which are then used to recursively render the sub-trees. 

2. **options** - Options to change the `rowHeight`, `indentWidth` and `showLines` properties of the Tree.

#### Slots
Added slots to override the label, icon or the complete node. Documented the slot usage and all other details in the Storybook docs.

<br>

<details>

<summary> Screen Recording </summary>

<br>

https://github.com/user-attachments/assets/1cc5f169-cc8b-4624-8023-f2db4b45d3c3

</details>

2024-08-21 09:45 UTC, ruchamahabal commented on src/components/Tree/Tree.vue
> +      showLines: true,
should we call this `showLevelMarkers` instead of showLines?

2024-08-21 10:02 UTC, ruchamahabal requested changes

2024-08-21 10:02 UTC, ruchamahabal commented on src/components/types/Tree.ts
> +  label: string
Should we also have a `nodeKey` in tree (like `rowKey` in list) since titles of 2 nodes could be same

2024-08-21 10:14 UTC, ruchamahabal commented
> . Although it is functional, unsure where to add this to maintain a clear separation between Frappe-specific and other components.

We can have a separate folder "frappe" under components for frappe specific components

2024-08-21 10:23 UTC, nextchamp-saqib commented
> We can have a separate folder "frappe" under components for frappe specific components

Also, we can rename `Tree` to `FrappeTree` because it is tied to `doctype` prop

2024-08-23 11:18 UTC, surajshetty3416 approved these changes
LGTM

2024-08-23 11:19 UTC, merged